name: Event Demo
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install-Dependencies
        run: npm install
        working-directory: ./my-react-app
      - name: Test-code
        run: npm test
        working-directory: ./my-react-app   
      - name: Build-code
        run: npm run build
        working-directory: ./my-react-app 
      - name: Deploy code
        run: echo "Deploying..."
